# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.05.02-25-gc5e453d
_src_path: gh:scientific-python/cookie
backend: hatch
email: alanlujan91@gmail.com
full_name: Alan Lujan
license: MIT
org: alanlujan91
project_name: moderation
project_short_description: A great package.
url: https://github.com/alanlujan91/MethodOfModeration
vcs: true
