"""Recompute every quantitative claim the PROSE of the paper makes.

Companion to `verify_table.py` (which regenerates `tbl:approx-errors` and the
Hermite variant) and `verify_boro_cnst.py` (which regenerates
`tbl:boro-cnst-art`). Those scripts own the tables; this one owns the numbers
that appear only in sentences of `content/paper/moderation_extended.md`:
human wealth and the worst-shock probability in the calibration paragraph,
the moderation-ratio landmarks quoted around `fig:ModerationRatio`, the
accuracy RATIOS the prose derives from the two tables, the grid-design ratios
quoted around `fig:GridExtent`, the slackness of the near-constraint envelope,
the return-risk containment range and volatility threshold, and the portfolio
section's calibration, kink points, chord bows and link comparisons.

Each check logs one line of the form

    [OK ] <what the paper says> | recomputed <value>

so a reader can diff the paper against the solver without reading code. A
claim is marked MISS when the recomputation falls outside the tolerance
printed with it; nothing here is tuned to force agreement, and `main` exits
non-zero if any claim misses.

One family of prose number is deliberately NOT recomputed here because it
already has a generator that prints it: the production-grid, bound-clamped and
horizon-sweep comparisons of `code/explorations/horserace/run_horserace.py`.
The grid-extent sweep is likewise generated by
`code/explorations/grid-extent/run_grid_extent.py`, but nothing there prints
the RATIOS the prose quotes, so `check_grid_extent` re-derives them from that
sweep's stamped output.

Run from the repository root:

    uv run python code/verify_prose_numbers.py
"""

from __future__ import annotations

import importlib.util
import json
import logging
import sys
import time
from pathlib import Path

import numpy as np
from HARK.ConsumptionSaving.ConsPortfolioModel import (
    PortfolioConsumerType,
    init_portfolio,
)
from HARK.distributions import Lognormal
from HARK.interpolation import LinearInterp

# Make `code/` importable regardless of caller CWD, without leaking a relative
# entry into sys.path.
_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

from moderation import (  # noqa: E402
    IndShockEGMConsumerType,
    IndShockMoMConsumerType,
    RiskyAssetMoMConsumerType,
    calc_return_factor_human_wealth,
    create_joint_distribution,
    moderate,
)
from portfolio import ModeratedShareFunc, PortfolioMoMConsumerType  # noqa: E402

# `_solve` and `_interval_max_errors` are reused rather than re-implemented so
# that the ratios quoted in prose are computed from exactly the numbers the
# table generator produces; duplicating the logic here would let the two drift.
from verify_table import (  # noqa: E402
    DENSE_GRID,
    M_BAR,
    N_EVAL,
    PARAMS,
    SPARSE_GRID,
    _interval_max_errors,
    _solve,
)

logger = logging.getLogger("verify_prose_numbers")

# Portfolio solves: the illustration grid, a far grid that reaches the
# Bodie-Merton-Samuelson crossing, and the converged scoring reference.
PORTFOLIO_GRID = {"cycles": 0, "aXtraMax": 100.0, "aXtraCount": 200, "tolerance": 1e-8}
PORTFOLIO_FAR = PORTFOLIO_GRID | {"aXtraMax": 20000.0, "aXtraCount": 800}
PORTFOLIO_REF = {
    "cycles": 0,
    "aXtraMax": 2000.0,
    "aXtraCount": 1000,
    "tolerance": 1e-8,
}

_RESULTS: list[tuple[str, str, str, bool]] = []


def _claim(section: str, wording: str, recomputed: str, *, ok: bool) -> None:
    """Record and log one paper claim against its recomputation."""
    _RESULTS.append((section, wording, recomputed, ok))
    logger.info(
        "  [%s] paper: %s | recomputed: %s",
        "OK " if ok else "MISS",
        wording,
        recomputed,
    )


def _note(text: str) -> None:
    """Log a supporting quantity the paper does not itself quote."""
    logger.info("       (%s)", text)


def _close(value: float, stated: float, rtol: float) -> bool:
    return bool(abs(value - stated) <= rtol * abs(stated))


# ---------------------------------------------------------------------------
# Section: Benchmark / calibration paragraph
# ---------------------------------------------------------------------------


def check_calibration() -> None:
    """Human wealth, the worst-shock probability, and the natural constraint."""
    logger.info("== Calibration paragraph (Benchmark section) ==")
    rfree = PARAMS["Rfree"][0]

    finite = IndShockMoMConsumerType(**(PARAMS | SPARSE_GRID))
    finite.solve()
    sol = finite.solution[0]

    _claim(
        "calibration",
        "h_{T-1} = 1/Rfree ~ 0.98",
        f"hNrm(T-1) = {sol.hNrm:.6f}, 1/Rfree = {1.0 / rfree:.6f}",
        ok=_close(sol.hNrm, 1.0 / rfree, 1e-10) and round(sol.hNrm, 2) == 0.98,
    )

    infinite = IndShockMoMConsumerType(**(PARAMS | SPARSE_GRID | {"cycles": 0}))
    infinite.solve()
    h_inf = infinite.solution[0].hNrm
    _claim(
        "calibration",
        "infinite-horizon human wealth is 50",
        f"hNrm(inf) = {h_inf:.6f}, 1/(Rfree-1) = {1.0 / (rfree - 1.0):.6f} "
        "(rtol 1e-4: the solved value carries the solver's own convergence "
        "tolerance)",
        ok=_close(h_inf, 1.0 / (rfree - 1.0), 1e-4),
    )

    # The worst transitory draw and its probability, straight off the solver's
    # own discretized income process (seven equiprobable positive points).
    dstn = finite.IncShkDstn[0]
    tran = np.asarray(dstn.atoms[1], dtype=float)
    pmv = np.asarray(dstn.pmv, dtype=float)
    tran_min = float(tran.min())
    worst_prob = float(pmv[tran == tran_min].sum())
    _claim(
        "calibration",
        "WorstProb = 1/7 (worst draw is one point of a seven-point grid)",
        f"WorstProb = {worst_prob:.6f}, 1/7 = {1 / 7:.6f}, grid size = {tran.size}",
        ok=_close(worst_prob, 1 / 7, 1e-10),
    )
    _claim(
        "calibration",
        "no zero-income atom: worst draw is strictly positive",
        f"tranShkMin = {tran_min:.6e}",
        ok=tran_min > 0.0,
    )
    _claim(
        "calibration",
        "the natural borrowing constraint is negative",
        f"mNrmMin = {sol.mNrmMin:.6f}, -tranShkMin/Rfree = {-tran_min / rfree:.6f}",
        ok=sol.mNrmMin < 0.0,
    )
    _note(f"MPCmin = {sol.MPCmin:.6f}, MPCmax = {sol.MPCmax:.6f}")

    # Table 1 caption: the five endogenous gridpoints. The MoM x_list carries a
    # duplicated mNrmMin entry at the front and an augmentation point at the
    # back; the EGM gridpoints proper are the five in between.
    grid_pts = np.asarray(sol.cFunc.x_list)[1:6]
    quoted = np.array([-0.13, 2.34, 4.47, 6.57, 8.64])
    _claim(
        "calibration",
        "Table 1 gridpoints m_0..m_4 = -0.13, 2.34, 4.47, 6.57, 8.64",
        "solved gridpoints = " + ", ".join(f"{m:.3f}" for m in grid_pts),
        ok=grid_pts.size == 5 and bool(np.all(np.abs(grid_pts - quoted) < 0.006)),
    )


# ---------------------------------------------------------------------------
# Section: The moderation ratio (fig:ModerationRatio)
# ---------------------------------------------------------------------------


def check_moderation_ratio() -> None:
    """Bracket width, its share of the optimist's rule, and omega's landmarks."""
    logger.info("== Moderation ratio (fig:ModerationRatio paragraph) ==")
    agent = IndShockMoMConsumerType(**(PARAMS | SPARSE_GRID))
    agent.solve()
    sol = agent.solution[0]
    c_opt, c_pes, c_real = sol.Optimist.cFunc, sol.Pessimist.cFunc, sol.cFunc

    widths = np.array([float(c_opt(x) - c_pes(x)) for x in (0.5, 5.0, 20.0)])
    # hNrmEx is the gap between the two human wealths, hNrmOpt - hNrmPes, and
    # mNrmMin = -hNrmPes, so hNrmEx = hNrm + mNrmMin.
    analytic_width = sol.MPCmin * (sol.hNrm + sol.mNrmMin)
    _claim(
        "moderation ratio",
        "the bracket has constant width MPCmin * hNrmEx",
        f"cOpt-cPes at m = 0.5, 5, 20: {widths[0]:.8f}, {widths[1]:.8f}, "
        f"{widths[2]:.8f}; MPCmin*hNrmEx = {analytic_width:.8f}",
        ok=bool(np.ptp(widths) < 1e-10)
        and _close(float(widths[0]), float(analytic_width), 1e-8),
    )

    m_near = sol.mNrmMin + 1e-6
    share_near = float((c_opt(m_near) - c_pes(m_near)) / c_opt(m_near))
    share_10 = float((c_opt(10.0) - c_pes(10.0)) / c_opt(10.0))
    _claim(
        "moderation ratio",
        "in levels the bracket is more than half of the optimist's consumption "
        "near the constraint",
        f"(cOpt-cPes)/cOpt at m = mNrmMin+1e-6 is {share_near:.4f}",
        ok=share_near > 0.5,
    )
    _claim(
        "moderation ratio",
        "and under a tenth of it by m = 10",
        f"(cOpt-cPes)/cOpt at m = 10 is {share_10:.4f}",
        ok=share_10 < 0.1,
    )

    grid = np.linspace(sol.mNrmMin + 1e-9, 30.0, 600_001)
    omega = moderate(grid, c_opt, c_real(grid), c_pes)
    cross_half = float(grid[int(np.argmax(omega >= 0.5))])
    omega_15 = float(omega[int(np.argmin(np.abs(grid - 15.0)))])
    _claim(
        "moderation ratio",
        "omega climbs through 0.5 near m = 2.3",
        f"first crossing of 0.5 at m = {cross_half:.4f}",
        ok=_close(cross_half, 2.3, 0.05),
    )
    _claim(
        "moderation ratio",
        "and past 0.8 by m = 15",
        f"omega(15) = {omega_15:.4f}",
        ok=omega_15 > 0.8,
    )
    _claim(
        "moderation ratio",
        "omega climbs from zero at the constraint (omega in (0,1) strictly)",
        f"omega range over (mNrmMin, 30] = [{omega.min():.4f}, {omega.max():.4f}]",
        ok=bool(omega.min() > 0.0) and bool(omega.max() < 1.0),
    )
    cross_08 = float(grid[int(np.argmax(omega >= 0.8))])
    _note(f"omega first reaches 0.8 at m = {cross_08:.4f}")


# ---------------------------------------------------------------------------
# Section: accuracy ratios quoted in prose around the two tables
# ---------------------------------------------------------------------------


def _table_errors(
    *,
    cubic: bool = False,
    perm_shk: bool = False,
) -> tuple[list[float], list[float]]:
    """EGM and MoM interval errors, exactly as `verify_table` computes them."""
    params = PARAMS | {"CubicBool": True} if cubic else PARAMS
    if perm_shk:
        params = params | {"PermShkStd": [0.1], "PermShkCount": 5}
    truth = _solve(IndShockEGMConsumerType, params, DENSE_GRID)
    egm = _solve(IndShockEGMConsumerType, params, SPARSE_GRID)
    mom = _solve(IndShockMoMConsumerType, params, SPARSE_GRID)
    grid_pts = np.array(egm.cFunc.x_list)[1:]
    return (
        _interval_max_errors(truth.cFunc, egm.cFunc, grid_pts, M_BAR, N_EVAL),
        _interval_max_errors(truth.cFunc, mom.cFunc, grid_pts, M_BAR, N_EVAL),
    )


def check_accuracy_ratios() -> None:
    """The EGM/MoM ratios the prose derives from tbl:approx-errors and its twin."""
    logger.info("== Accuracy ratios quoted in prose (Table 1 and the cubic twin) ==")
    egm_lin, mom_lin = _table_errors()
    egm_cub, mom_cub = _table_errors(cubic=True)
    ratio_lin = [e / m for e, m in zip(egm_lin, mom_lin, strict=True)]
    ratio_cub = [e / m for e, m in zip(egm_cub, mom_cub, strict=True)]
    _note("linear EGM  = " + ", ".join(f"{e:.3e}" for e in egm_lin))
    _note("linear MoM  = " + ", ".join(f"{e:.3e}" for e in mom_lin))
    _note("linear ratio= " + ", ".join(f"{r:.2f}" for r in ratio_lin))
    _note("cubic  EGM  = " + ", ".join(f"{e:.3e}" for e in egm_cub))
    _note("cubic  MoM  = " + ", ".join(f"{e:.3e}" for e in mom_cub))
    _note("cubic  ratio= " + ", ".join(f"{r:.2f}" for r in ratio_cub))

    _claim(
        "abstract / Table 1",
        "MoM more accurate than EGM in every interval",
        f"min ratio over the five columns = {min(ratio_lin):.2f}",
        ok=min(ratio_lin) > 1.0,
    )
    _claim(
        "Table 1 prose",
        "in the first interval we manage about three and a half times",
        f"ratio[m0,m1] = {ratio_lin[0]:.2f} (rtol 0.10 on 3.5)",
        ok=_close(ratio_lin[0], 3.5, 0.10),
    )
    _claim(
        "Table 1 prose",
        "more than an order of magnitude in the remaining interior intervals",
        "interior ratios = " + ", ".join(f"{r:.2f}" for r in ratio_lin[1:4]),
        ok=min(ratio_lin[1:4]) > 10.0,
    )
    _claim(
        "abstract / Table 1 prose",
        "roughly forty-six times more accurate in the extrapolation region",
        f"ratio[m4,mbar] = {ratio_lin[4]:.2f} (rtol 0.05 on 46)",
        ok=_close(ratio_lin[4], 46.0, 0.05),
    )

    fall_first = mom_lin[0] / mom_cub[0]
    fall_rest = [mom_lin[j] / mom_cub[j] for j in (1, 2, 3)]
    _claim(
        "cubic prose",
        "moderation's interior error falls by a factor of five in the first interval",
        f"MoM linear/cubic in [m0,m1] = {fall_first:.2f} (rtol 0.15 on 5)",
        ok=_close(fall_first, 5.0, 0.15),
    )
    _claim(
        "cubic prose",
        "and by roughly two to three orders of magnitude in the rest",
        "MoM linear/cubic in the other interior intervals = "
        + ", ".join(f"{f:.1f}" for f in fall_rest),
        ok=min(fall_rest) >= 10.0 and max(fall_rest) <= 3000.0,
    )
    _claim(
        "cubic prose",
        "beyond the first interval the advantage grows from eleven or "
        "seventeen times under linear",
        "linear interior ratios = " + ", ".join(f"{r:.1f}" for r in ratio_lin[1:4]),
        ok=round(min(ratio_lin[1:4])) == 11 and round(max(ratio_lin[1:4])) == 17,
    )
    _claim(
        "cubic prose",
        "to between thirty-eight and fifty-six times under cubic",
        "cubic interior ratios = " + ", ".join(f"{r:.1f}" for r in ratio_cub[1:4]),
        ok=min(ratio_cub[1:4]) >= 38.0 and max(ratio_cub[1:4]) <= 56.0,
    )
    # The paper's stated endpoints are recoverable only from the ROUNDED table
    # entries; the raw solver ratios sit inside them, so "between" holds but
    # neither endpoint is attained.
    rounded = [
        round(float(f"{e:.2g}") / float(f"{m:.2g}"), 1)
        for e, m in zip(egm_cub[1:4], mom_cub[1:4], strict=True)
    ]
    _note(
        "recomputed from the two-significant-digit table entries the same "
        "ratios are " + ", ".join(f"{r:.1f}" for r in rounded),
    )
    _claim(
        "cubic prose",
        "in the first interval it slips from about three and a half times to three",
        f"linear {ratio_lin[0]:.2f} -> cubic {ratio_cub[0]:.2f} (rtol 0.10 on 3.0)",
        ok=_close(ratio_cub[0], 3.0, 0.10),
    )
    _claim(
        "cubic prose",
        "beyond the top gridpoint moderation's error barely moves, 3.0(-3) to 2.4(-3)",
        f"MoM extrapolation error {mom_lin[4]:.2e} (linear) -> "
        f"{mom_cub[4]:.2e} (cubic)",
        ok=_close(mom_lin[4], 3.0e-3, 0.06) and _close(mom_cub[4], 2.4e-3, 0.06),
    )
    _claim(
        "cubic prose",
        "the ratio between the methods is forty-six in one table and forty-five "
        "in the other",
        f"extrapolation ratio linear {ratio_lin[4]:.2f}, cubic {ratio_cub[4]:.2f}",
        ok=_close(ratio_lin[4], 46.0, 0.05) and _close(ratio_cub[4], 45.0, 0.05),
    )

    # The permanent-shock footnote: verify_table carries the switch that prints
    # the levels, but the "less than a factor of two" comparison against the
    # baseline table appears only in the footnote's prose.
    egm_ps, mom_ps = _table_errors(perm_shk=True)
    moves = [
        max(a / b, b / a)
        for a, b in zip(egm_ps + mom_ps, egm_lin + mom_lin, strict=True)
    ]
    _note("permshk EGM = " + ", ".join(f"{e:.1e}" for e in egm_ps))
    _note("permshk MoM = " + ", ".join(f"{e:.1e}" for e in mom_ps))
    _claim(
        "permanent-shock footnote",
        "restoring permanent shocks moves every entry of Table 1 by less than a "
        "factor of two",
        f"largest entrywise move = {max(moves):.2f}x",
        ok=max(moves) < 2.0,
    )
    _claim(
        "permanent-shock footnote",
        "and leaves the ordering intact",
        "MoM <= EGM in every column: "
        f"{all(m <= e for m, e in zip(mom_ps, egm_ps, strict=True))}",
        ok=all(m <= e for m, e in zip(mom_ps, egm_ps, strict=True)),
    )


# ---------------------------------------------------------------------------
# Section: grid design (fig:GridExtent paragraph)
# ---------------------------------------------------------------------------

_GRID_EXTENT_DIR = _THIS_DIR / "explorations" / "grid-extent"


def _load_grid_extent() -> dict[str, dict] | None:
    """Variants from the grid-extent sweep, refusing a stale JSON.

    `run_grid_extent.py` is the generator of record; this only re-derives the
    RATIOS the paper quotes from its output, since the sweep itself is too
    slow to repeat here.
    """
    payload = _GRID_EXTENT_DIR / "grid_extent.json"
    if not payload.exists():
        return None
    spec = importlib.util.spec_from_file_location(
        "run_grid_extent",
        _GRID_EXTENT_DIR / "run_grid_extent.py",
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    result = json.loads(payload.read_text())
    expected = {k: repr(v) for k, v in sorted(module.PARAMS.items())}
    if result.get("params") != expected:
        msg = (
            "grid_extent.json was produced by different parameters than the "
            "current run_grid_extent.py; rerun that sweep before trusting "
            "these ratios."
        )
        raise RuntimeError(msg)
    return {variant["label"]: variant for variant in result["variants"]}


def check_grid_extent() -> None:
    """The density-versus-extent ratios quoted around fig:GridExtent."""
    logger.info("== Grid design (fig:GridExtent paragraph) ==")
    variants = _load_grid_extent()
    if variants is None:
        logger.warning(
            "  grid_extent.json is absent; run "
            "code/explorations/grid-extent/run_grid_extent.py to cover the "
            "grid-extent prose claims.",
        )
        return

    def err(label: str) -> float:
        return float(variants[label]["max_abs_err"])

    base = err("paper-linear-5pt")
    density = err("count30-same-extent") / base
    _claim(
        "grid design",
        "raising the point count from five to thirty at the five-point grid's "
        "own extent does not improve the beyond-grid error at all (it rises "
        "slightly)",
        f"beyond-grid error {base:.3e} -> {err('count30-same-extent'):.3e}, "
        f"a factor of {density:.2f}",
        ok=density > 1.0,
    )
    two_h = [base / err(f"nest{n}-a2h") for n in (2, 3)]
    _claim(
        "grid design",
        "raising the grid top to twice human wealth improves it by roughly an "
        "order of magnitude",
        "improvement over the five-point extent = "
        + ", ".join(f"nest{n}: {r:.1f}x" for n, r in zip((2, 3), two_h, strict=True)),
        ok=all(3.0 <= r <= 30.0 for r in two_h),
    )
    further = [err(f"nest{n}-a2h") / err(f"nest{n}-a4h") for n in (2, 3)]
    _claim(
        "grid design",
        "with a further factor of two by four times human wealth",
        "2h -> 4h improvement = "
        + ", ".join(f"nest{n}: {r:.2f}x" for n, r in zip((2, 3), further, strict=True)),
        ok=all(_close(r, 2.0, 0.25) for r in further),
    )
    # "A third more accurate" reads as a third less error, so score the
    # fractional reduction below rather than the ratio of the two errors.
    reductions = [1.0 - err(f"nest2-a{r}") / err(f"nest3-a{r}") for r in ("2h", "4h")]
    _claim(
        "grid design",
        "past human wealth, double-exponential spacing is about a third more "
        "accurate beyond the grid than triple",
        "error reduction of nest2 against nest3 = "
        + ", ".join(
            f"a{r}: {100 * x:.0f}%"
            for r, x in zip(("2h", "4h"), reductions, strict=True)
        ),
        ok=all(0.25 <= x <= 0.42 for x in reductions),
    )
    coincide = [
        abs(1.0 - err(f"nest2-a{r}") / err(f"nest3-a{r}")) for r in ("0.5h", "1h")
    ]
    _claim(
        "grid design",
        "the two spacings coincide at small extents",
        "relative gap at a=0.5h, 1h = "
        + ", ".join(f"{100 * x:.1f}%" for x in coincide),
        ok=all(x < 0.02 for x in coincide),
    )


# ---------------------------------------------------------------------------
# Section: A Tighter Upper Bound (the near-constraint envelope)
# ---------------------------------------------------------------------------


def check_envelope_slack() -> None:
    """Is the tighter bound MPCmax*mNrmEx slack over the tabulated range?"""
    logger.info("== Near-constraint envelope (A Tighter Upper Bound) ==")
    agent = IndShockMoMConsumerType(**(PARAMS | SPARSE_GRID))
    agent.solve()
    sol = agent.solution[0]
    egm = IndShockEGMConsumerType(**(PARAMS | SPARSE_GRID))
    egm.solve()
    # The table's first tabulated gridpoint: verify_table drops index 0 (the
    # natural borrowing constraint) and starts the intervals at index 1.
    m0 = float(np.array(egm.solution[0].cFunc.x_list)[1])

    def bound(m: np.ndarray) -> np.ndarray:
        """eq:cFuncLowerEnvelope's tighter branch, MPCmax * (m - mNrmMin)."""
        return sol.MPCmax * (m - sol.mNrmMin)

    probe = np.linspace(m0 + 1e-8, M_BAR, 400_001)
    gap = bound(probe) - sol.cFunc(probe)
    _claim(
        "tighter upper bound",
        "the envelope is slack over the tabulated range under the natural constraint",
        f"min(bound - cMoM) on [m0={m0:.4f}, {M_BAR:.0f}] = {gap.min():.3e}",
        ok=bool(gap.min() > 0.0),
    )

    fine = np.linspace(sol.mNrmMin, m0 + 0.01, 2_000_001)
    binding = fine[(bound(fine) - sol.cFunc(fine)) <= 0.0]
    width = float(binding.max() - binding.min()) if binding.size else 0.0
    _claim(
        "tighter upper bound",
        "under a natural constraint the rule touches the bound only as "
        "m -> mNrmMin (the envelope has nothing to do)",
        f"binding set is [{binding.min():.6f}, {binding.max():.6f}], width "
        f"{width:.4e}, entirely below m0 = {m0:.4f}: "
        f"{bool(binding.size and binding.max() < m0)}",
        ok=bool(binding.size == 0 or (binding.max() < m0 and width < 0.01)),
    )
    _claim(
        "tighter upper bound",
        "the bound carries c(mNrmMin) = 0 for free",
        f"bound(mNrmMin) = {float(bound(np.array([sol.mNrmMin]))[0]):.3e}, "
        f"cMoM(mNrmMin) = {float(sol.cFunc(np.array([sol.mNrmMin]))[0]):.3e}",
        ok=abs(float(sol.cFunc(np.array([sol.mNrmMin]))[0])) < 1e-12,
    )
    _note(f"MPCmax = {sol.MPCmax:.6f} < 1, so the bound lies inside the budget line")


# ---------------------------------------------------------------------------
# Section: Stochastic Rate of Return
# ---------------------------------------------------------------------------


def check_return_risk() -> None:
    """Bracket containment under return risk, and the volatility threshold."""
    logger.info("== Return risk (Stochastic Rate of Return section) ==")
    # In this module RiskyStd is a LEVEL standard deviation, which is why the
    # paper words the calibration as "a level standard deviation of 0.08".
    risky_std = 0.08
    params = PARAMS | {"RiskyAvg": PARAMS["Rfree"][0], "RiskyStd": risky_std}
    agent = RiskyAssetMoMConsumerType(**params)
    agent.solve()
    sol = agent.solution[0]

    n_probe = 2000
    probe = np.linspace(sol.mNrmMin + 0.01, 10.0, n_probe)
    c_real = sol.cFunc(probe)
    c_opt = sol.OptimistStochastic.cFunc(probe)
    c_pes = sol.PessimistStochastic.cFunc(probe)
    omega = (c_real - c_pes) / (c_opt - c_pes)
    _claim(
        "return risk",
        "the realist's rule stays strictly inside the bracket at every one of "
        "two thousand probe points between the constraint and m = 10",
        f"{probe.size} probes on [{probe[0]:.4f}, {probe[-1]:.1f}], strictly "
        f"inside: {bool(np.all((omega > 0) & (omega < 1)))}",
        ok=probe.size == n_probe and bool(np.all((omega > 0) & (omega < 1))),
    )
    _claim(
        "return risk",
        "the moderation ratio ranges over [0.005, 0.770]",
        f"omega range = [{omega.min():.4f}, {omega.max():.4f}] "
        "(rtol 0.05 on each endpoint)",
        ok=_close(float(omega.min()), 0.005, 0.05)
        and _close(float(omega.max()), 0.770, 0.05),
    )

    crra = PARAMS["CRRA"]
    inc_dstn = agent.IncShkDstn[0]

    def moments(std: float) -> tuple[float, float]:
        joint = create_joint_distribution(inc_dstn, params["RiskyAvg"], std)
        ret = np.asarray(joint.atoms[2], dtype=float)
        pmv = np.asarray(joint.pmv, dtype=float)
        return (
            float(np.sum(pmv * ret ** (1.0 - crra))),
            float(np.sum(pmv * ret ** (-crra))),
        )

    num_08, den_08 = moments(risky_std)
    _claim(
        "return risk",
        "the calibration satisfies E[R^-rho] < E[R^(1-rho)] at RiskyStd = 0.08",
        f"E[R^(1-rho)] = {num_08:.6f}, E[R^-rho] = {den_08:.6f}",
        ok=den_08 < num_08,
    )

    # Locate the volatility at which the two moments cross.
    grid = np.arange(0.02, 0.2005, 0.0005)
    holds = np.array([moments(float(s))[1] < moments(float(s))[0] for s in grid])
    flips = np.flatnonzero(np.diff(holds.astype(int)) != 0)
    threshold = float(grid[flips[0] + 1]) if flips.size else float("nan")
    _claim(
        "return risk footnote",
        "E[R^-rho] overtakes E[R^(1-rho)] near a volatility of 0.10",
        f"crossing at RiskyStd = {threshold:.4f} (rtol 0.10 on 0.10)",
        ok=_close(threshold, 0.10, 0.10),
    )

    joint_08 = create_joint_distribution(inc_dstn, params["RiskyAvg"], risky_std)
    shadow = calc_return_factor_human_wealth(joint_08, crra)
    _note(
        f"shadow riskless return Rtilde = E[R^(1-rho)]/E[R^-rho] = "
        f"{shadow:.6f} against Rfree = {PARAMS['Rfree'][0]}; hNrmOpt = "
        f"{1.0 / (shadow - 1.0):.4f}",
    )


# ---------------------------------------------------------------------------
# Section: Portfolio Choice
# ---------------------------------------------------------------------------


def check_portfolio_calibration(agent, sigma_star: float) -> None:
    """The stated parameter values and the Campbell-Viceira myopic share."""
    stated = {
        "CRRA": 5.0,
        "DiscFac": 0.9,
        "LivPrb": [0.98],
        "Rfree": [1.03],
        "PermGroFac": [1.01],
        "PermShkStd": [0.1],
        "TranShkStd": [0.1],
        "UnempPrb": 0.05,
        "IncUnemp": 0.3,
        "RiskyAvg": 1.08,
    }
    mismatched = {
        key: (init_portfolio[key], value)
        for key, value in stated.items()
        if np.any(np.asarray(init_portfolio[key]) != np.asarray(value))
    }
    _claim(
        "portfolio calibration",
        "CRRA 5, DiscFac 0.9, LivPrb 0.98, Rfree 1.03, PermGroFac 1.01, "
        "shock std 0.1 each, 5% unemployment paying 0.3, RiskyAvg 1.08",
        "all match init_portfolio" if not mismatched else f"mismatches {mismatched}",
        ok=not mismatched,
    )

    # HARK's `RiskyStd` could name either dispersion, so measure both. A fine
    # discretization pins the convention; the solver's own coarse RiskyDstn
    # then shows what the quadrature does to it.
    risky_avg = init_portfolio["RiskyAvg"]

    def _moments(dstn) -> tuple[float, float, float]:
        ret = np.asarray(np.atleast_2d(dstn.atoms)[0], dtype=float)
        pmv = np.asarray(dstn.pmv, dtype=float)
        mean_level = float(np.sum(pmv * ret))
        level_std = float(np.sqrt(np.sum(pmv * (ret - mean_level) ** 2)))
        mean_log = float(np.sum(pmv * np.log(ret)))
        log_std = float(np.sqrt(np.sum(pmv * (np.log(ret) - mean_log) ** 2)))
        return mean_level, log_std, level_std

    fine_mean, fine_log_std, fine_level_std = _moments(
        Lognormal(
            mean=risky_avg,
            sigma=init_portfolio["RiskyStd"],
        ).discretize(2000, method="equiprobable"),
    )
    _claim(
        "portfolio calibration",
        "risky asset with mean gross return 1.08 and log standard deviation 0.184",
        f"E[R] = {fine_mean:.4f}, log std = {fine_log_std:.4f} (level std "
        f"{fine_level_std:.4f}), so HARK's RiskyStd = "
        f"{init_portfolio['RiskyStd']:.6f} is the LOG std",
        ok=_close(fine_mean, 1.08, 0.005) and _close(fine_log_std, 0.184, 0.01),
    )
    solver_mean, solver_log_std, _ = _moments(agent.RiskyDstn)
    _note(
        f"the solver's own {np.asarray(agent.RiskyDstn.pmv).size}-node "
        f"equiprobable quadrature carries E[R] = {solver_mean:.4f} and log std "
        f"{solver_log_std:.4f}, compressed relative to the continuous 0.184",
    )

    crra = init_portfolio["CRRA"]
    std_log = init_portfolio["RiskyStd"]
    log_premium = float(np.log(risky_avg) - np.log(init_portfolio["Rfree"][0]))
    cv_share = log_premium / (crra * std_log**2)
    _claim(
        "portfolio",
        "the Campbell-Viceira log-linear share equityPrem/(CRRA*std^2) gives 0.28",
        f"equityPrem = log(E[R]) - log(Rfree) = {log_premium:.6f}, "
        f"/(CRRA * {std_log:.4f}^2) = {cv_share:.4f}",
        ok=_close(cv_share, 0.28, 0.02),
    )
    _claim(
        "portfolio",
        "against the 0.31 solved on the discretized return process",
        f"ShareLimit = {sigma_star:.4f}",
        ok=_close(sigma_star, 0.31, 0.02),
    )


def check_portfolio_bounds(sol_far, sigma_star: float) -> None:
    """The kink point and the crossing of the Bodie-Merton-Samuelson ceiling."""
    h_nrm = float(sol_far.hNrm)
    _note(f"portfolio hNrm = {h_nrm:.4f}")

    m_release = float(sol_far.ShareFuncAdj.mRelease)
    _claim(
        "portfolio",
        "the investor leaves the constraint at m = 7.25",
        f"mRelease (solved kink) = {m_release:.4f} (rtol 0.02 on 7.25)",
        ok=_close(m_release, 7.25, 0.02),
    )

    grid = np.geomspace(10.0, 200_000.0, 400_000)
    solved = sol_far.ShareFuncAdjDirect(grid)
    ceiling = sigma_star * (1.0 + h_nrm / grid)
    sign_change = np.flatnonzero(np.diff(np.sign(solved - ceiling)) != 0)
    crossing = float(grid[sign_change[0]]) if sign_change.size else float("nan")
    # The paper no longer quotes the crossing point (cut 2026-08-26); the claim
    # that survives is that the solved share's gap above sigma* closes more
    # slowly than the ceiling's h/m, which is exactly what a crossing shows.
    _claim(
        "portfolio",
        "the Bodie-Merton-Samuelson ceiling is crossed: the solved share's gap "
        "closes more slowly than h/m",
        f"solved share crosses the ceiling at m = {crossing:,.0f}",
        ok=np.isfinite(crossing),
    )


def check_portfolio_links(sol_far, ref_sol, sigma_star: float) -> None:
    """Chord bows of the candidate transforms, and the five-node link scores."""
    grid = np.geomspace(10.0, 1000.0, 300)
    share = sol_far.ShareFuncAdjDirect(grid)
    omega = np.clip((share - sigma_star) / (1.0 - sigma_star), 1e-12, 1 - 1e-12)
    bows = {}
    for label, values in (
        ("share", share),
        ("logit", np.log(omega) - np.log1p(-omega)),
        ("log omega", np.log(omega)),
    ):
        scaled = (values - values.min()) / (values.max() - values.min())
        chord = np.linspace(scaled[0], scaled[-1], scaled.size)
        bows[label] = 100.0 * float(np.abs(scaled - chord).max())
    _claim(
        "portfolio",
        "over m in [10, 1e3] the untransformed share departs from its chord by "
        "39 percent of the plotted range",
        f"share bow = {bows['share']:.1f}% (rtol 0.05 on 39)",
        ok=_close(bows["share"], 39.0, 0.05),
    )
    _claim(
        "portfolio",
        "and the logit by 14 percent",
        f"logit bow = {bows['logit']:.1f}% (rtol 0.08 on 14)",
        ok=_close(bows["logit"], 14.0, 0.08),
    )
    _claim(
        "portfolio",
        "log(shareModRte) departs by 1.4 percent",
        f"log-omega bow = {bows['log omega']:.2f}% (rtol 0.10 on 1.4)",
        ok=_close(bows["log omega"], 1.4, 0.10),
    )

    probe = np.geomspace(25.0, 100.0, 400)
    truth = ref_sol.ShareFuncAdj(probe)
    nodes = np.geomspace(25.0, 100.0, 5)
    s_nodes = ref_sol.ShareFuncAdj(nodes)
    om_nodes = np.clip(
        (s_nodes - sigma_star) / (1.0 - sigma_star),
        1e-12,
        1 - 1e-12,
    )
    baseline = float(
        np.abs(LinearInterp(nodes, s_nodes, lower_extrap=True)(probe) - truth).max(),
    )
    links = {
        "log": (np.log, np.exp),
        "logit": (
            lambda o: np.log(o) - np.log1p(-o),
            lambda z: 1.0 / (1.0 + np.exp(-z)),
        ),
        "cloglog": (
            lambda o: np.log(-np.log1p(-o)),
            lambda z: -np.expm1(-np.exp(z)),
        ),
    }
    ratios = {}
    for name, (fwd, inv) in links.items():
        interpolated = LinearInterp(
            np.log(nodes),
            fwd(om_nodes),
            lower_extrap=True,
        )(np.log(probe))
        approx = sigma_star + (1.0 - sigma_star) * inv(interpolated)
        ratios[name] = baseline / float(np.abs(approx - truth).max())
    _note(f"five-node baseline (interpolate the share itself) max err {baseline:.3e}")
    _claim(
        "portfolio",
        "with five nodes the logarithm is roughly a hundred times more accurate "
        "than interpolating the share itself",
        f"log ratio = {ratios['log']:.1f}x (rtol 0.20 on 100)",
        ok=_close(ratios["log"], 100.0, 0.20),
    )
    _claim(
        "portfolio",
        "the complementary log-log eight times",
        f"cloglog ratio = {ratios['cloglog']:.1f}x (rtol 0.20 on 8)",
        ok=_close(ratios["cloglog"], 8.0, 0.20),
    )
    _claim(
        "portfolio",
        "and the logit four times",
        f"logit ratio = {ratios['logit']:.1f}x (rtol 0.20 on 4)",
        ok=_close(ratios["logit"], 4.0, 0.20),
    )


def check_portfolio_accuracy(ref_sol, sigma_star: float) -> None:
    """Node-count sweeps clear of the kink and on a grid spanning it."""
    probe = np.geomspace(25.0, 100.0, 400)
    truth = ref_sol.ShareFuncAdj(probe)
    clear_ratios = {}
    for n in (4, 5, 7):
        nodes = np.geomspace(25.0, 100.0, n)
        s_nodes = ref_sol.ShareFuncAdj(nodes)
        moderated = ModeratedShareFunc(nodes, s_nodes, sigma_star)
        linear = np.abs(
            LinearInterp(nodes, s_nodes, lower_extrap=True)(probe) - truth,
        )
        clear_ratios[n] = float(linear.max() / np.abs(moderated(probe) - truth).max())
    _note(
        "clear-of-kink ratios by node count: "
        + ", ".join(f"n={n}: {r:.1f}x" for n, r in clear_ratios.items()),
    )
    lo, hi = min(clear_ratios.values()), max(clear_ratios.values())
    _claim(
        "portfolio",
        "clear of the kink, moderation is between seventy and a hundred and "
        "fifty times more accurate on four to seven nodes",
        f"ratio range = [{lo:.1f}x, {hi:.1f}x] (bounds compared after rounding "
        "to the nearest ten)",
        ok=round(lo / 10.0) * 10 >= 70.0 and round(hi / 10.0) * 10 <= 150.0,
    )
    _claim(
        "portfolio",
        "with the advantage growing as the grid coarsens",
        "ratios by node count (4, 5, 7) = "
        + ", ".join(f"{clear_ratios[n]:.1f}" for n in (4, 5, 7)),
        ok=clear_ratios[4] > clear_ratios[5] > clear_ratios[7],
    )

    probe2 = np.geomspace(1.0, 100.0, 2000)
    truth2 = ref_sol.ShareFuncAdj(probe2)
    tail_ratios, mid_ratios = {}, {}
    for n in (8, 12, 20):
        nodes = np.geomspace(1.0, 100.0, n)
        s_nodes = ref_sol.ShareFuncAdj(nodes)
        moderated = ModeratedShareFunc(nodes, s_nodes, sigma_star)
        linear = np.abs(
            LinearInterp(nodes, s_nodes, lower_extrap=True)(probe2) - truth2,
        )
        mod_err = np.abs(moderated(probe2) - truth2)
        tail = probe2 >= moderated.mBridge
        mid = (probe2 > moderated.mRelease) & (probe2 < moderated.mBridge)
        tail_ratios[n] = float(linear[tail].max() / mod_err[tail].max())
        mid_ratios[n] = float(linear[mid].max() / mod_err[mid].max())
    _note(
        "spanning-grid tail ratios: "
        + ", ".join(f"n={n}: {r:.1f}x" for n, r in tail_ratios.items()),
    )
    _note(
        "spanning-grid transition ratios: "
        + ", ".join(f"n={n}: {r:.2f}x" for n, r in mid_ratios.items()),
    )
    _claim(
        "portfolio",
        "on a grid spanning the constrained region our tail advantage runs from "
        "twelve to over a hundred times",
        f"tail ratio range = [{min(tail_ratios.values()):.1f}x, "
        f"{max(tail_ratios.values()):.1f}x]",
        ok=round(min(tail_ratios.values())) >= 12 and max(tail_ratios.values()) > 100.0,
    )
    _claim(
        "portfolio",
        "across the transition it is about twice",
        f"transition ratio range = [{min(mid_ratios.values()):.2f}x, "
        f"{max(mid_ratios.values()):.2f}x]",
        ok=1.5 <= float(np.median(list(mid_ratios.values()))) <= 2.5,
    )


def check_portfolio() -> None:
    """Solve the portfolio problem once and run every portfolio-section check."""
    logger.info("== Portfolio choice ==")
    agent = PortfolioMoMConsumerType(**(init_portfolio | PORTFOLIO_GRID))
    agent.solve()
    sigma_star = float(agent.solution[0].ShareLimit)

    far = PortfolioMoMConsumerType(**(init_portfolio | PORTFOLIO_FAR))
    far.solve()
    sol_far = far.solution[0]

    reference = PortfolioConsumerType(**(init_portfolio | PORTFOLIO_REF))
    reference.solve()
    ref_sol = reference.solution[0]

    check_portfolio_calibration(agent, sigma_star)
    check_portfolio_bounds(sol_far, sigma_star)
    check_portfolio_links(sol_far, ref_sol, sigma_star)
    check_portfolio_accuracy(ref_sol, sigma_star)


def main() -> int:
    # `force=True` is needed because HARK's import path installs root logging
    # handlers that would otherwise suppress this script's INFO output.
    logging.basicConfig(level=logging.INFO, format="%(message)s", force=True)
    started = time.perf_counter()

    check_calibration()
    check_moderation_ratio()
    check_accuracy_ratios()
    check_grid_extent()
    check_envelope_slack()
    check_return_risk()
    check_portfolio()

    misses = [row for row in _RESULTS if not row[3]]
    logger.info("")
    logger.info(
        "Checked %d prose claims in %.1f s: %d match, %d miss.",
        len(_RESULTS),
        time.perf_counter() - started,
        len(_RESULTS) - len(misses),
        len(misses),
    )
    for section, wording, recomputed, _ in misses:
        logger.error("MISS [%s] %s -> %s", section, wording, recomputed)
    return 1 if misses else 0


if __name__ == "__main__":
    sys.exit(main())
